### PR TITLE
[6.2.5] memkind support

### PR DESCRIPTION
**Pull request by michalbiesek**
This change is [Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/149)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 30 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/149)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @michalbiesek)

___
*[redis.conf, line 2052 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/149#-MfguqaFB4VLfaNfFc_o:-MfguqaFB4VLfaNfFc_p:b97xwvp) ([raw file](https://github.com/memkeydb/memkeydb/blob/a77c7ec48d68e5a2c5091a1b220fd14a0f5dbd7a/redis.conf#L2052)):*
> ```
> #
> # ignore-warnings ARM64-COW-BUG
> ############################### MEMORY ALLOCATION CONFIGURATION #############################
> ```

nit: Add a newline above.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/149)* status: 29 of 30 files reviewed, all discussions resolved (waiting on @bratpiorka and @PatKamin)

___
*[redis.conf, line 2052 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/149#-MfguqaFB4VLfaNfFc_o:-MfgybYXE8dgrvsqrjvE:bb6un1j) ([raw file](https://github.com/memkeydb/memkeydb/blob/a77c7ec48d68e5a2c5091a1b220fd14a0f5dbd7a/redis.conf#L2052)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Add a newline above.
</blockquote></details>

Done

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 30 of 30 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
