### PR TITLE
Add a separate OOM handler for PMEM

### PR DESCRIPTION
**Pull request by bratpiorka**
- this handler first checks if there are any PMEM nodes in the system available for use by Memkind
  and if not - a descriptive error message is printed and allocator is switched to DRAM-only mode
- then the default OOM handler is called

---
This change is [Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/156)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
already reviewed in #154 

> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/156#-:-MmNmahJE13Lgdfsok_o:bmyn9zo)* status: 0 of 2 files reviewed, all discussions resolved

**Review by PatKamin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/156)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/zmalloc.c, line 263 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/156#-MmNnVzpEKKD5XP8Ixa7:-MmNnVzq239QlNTfq8dB:b-xehqdh) ([raw file](https://github.com/memkeydb/memkeydb/blob/e49e43773d31089dc85b6cdd5cee1975be55ee48/src/zmalloc.c#L263)):*
> ```C
> static void *zmalloc_pmem(size_t size) {
>     void *ptr = memkind_malloc(pmem_kind, size+PREFIX_SIZE);
>     if (!ptr) zmalloc_pmem_oom_handler(size);
> ```

Why removing errno?
___
*[src/zmalloc.c, line 277 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/156#-MmNnaKa5NYuUztqU4fT:-MmNnaKa5NYuUztqU4fU:b3kqx) ([raw file](https://github.com/memkeydb/memkeydb/blob/e49e43773d31089dc85b6cdd5cee1975be55ee48/src/zmalloc.c#L277)):*
> ```C
>     void *ptr = memkind_calloc(pmem_kind, 1, size+PREFIX_SIZE);
> 
>     if (!ptr) zmalloc_pmem_oom_handler(size);
> ```

.

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/156)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/zmalloc.c, line 263 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/156#-MmNnVzpEKKD5XP8Ixa7:-MmReKSU7X8D4OMCxF6Q:b72jbo6) ([raw file](https://github.com/memkeydb/memkeydb/blob/e49e43773d31089dc85b6cdd5cee1975be55ee48/src/zmalloc.c#L263)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Why removing errno?
</blockquote></details>

It is not set by Memkind to ENOMEM in this case. Note that in 6.2.5-devel branch this condition is also removed.

**Review by PatKamin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
