### PR TITLE
Add a separate OOM handler for PMEM

### PR DESCRIPTION
**Pull request by bratpiorka**
- this handler first checks if there are any PMEM nodes in the system available for use by Memkind
- if yes - the usual OOM handler is called
- if not - a descriptive error message is printed and
  Redis is gracefully shut down instead of crashing.

---
This change is [Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[src/zmalloc.c, line 290 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/154#-Mlxu_SL4rd-wzANs0WH:-Mlxu_SL4rd-wzANs0WI:b-bqtu72) ([raw file](https://github.com/memkeydb/memkeydb/blob/4dce305544a1270938db682fe072e27cc0308c1c/src/zmalloc.c#L290)):*
> ```C
> 
> static void zmalloc_pmem_oom_handler(size_t size) {
>     long int mask = 0;
> ```

unsigned long
___
*[src/zmalloc.c, line 297 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlxqALR8krtcNHTJi_x:-MlxqALR8krtcNHTJi_y:bqb2s7v) ([raw file](https://github.com/memkeydb/memkeydb/blob/4dce305544a1270938db682fe072e27cc0308c1c/src/zmalloc.c#L297)):*
> ```C
>         fprintf(stderr,"!!! is not working.\n");
>         fprintf(stderr,"!!! Please run \"numactl -H\" to see if it reports any PMEM NUMA nodes (nodes without\n");
>         fprintf(stderr,"!!! CPUs). If so, please provide a list of these nodes in the MEMKIND_KMEM_DAX_NODES\n");
> ```

MEMKIND_DAX_KMEM_NODES
___
*[src/zmalloc.c, line 309 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/154#-Mlxv3i_7xSIAQn3QP9T:-Mlxv3i_7xSIAQn3QP9U:b-ludzyw) ([raw file](https://github.com/memkeydb/memkeydb/blob/4dce305544a1270938db682fe072e27cc0308c1c/src/zmalloc.c#L309)):*
> ```C
> static void *zmalloc_pmem(size_t size) {
>     void *ptr = ztrymalloc_usable_pmem(size, NULL);
>     if (!ptr)  {
> ```

Fix whitespaces.

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[src/zmalloc.c, line 290 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/154#-Mlxu_SL4rd-wzANs0WH:-Mly2FiFDFzCfBGS2oKk:b-896fix) ([raw file](https://github.com/memkeydb/memkeydb/blob/4dce305544a1270938db682fe072e27cc0308c1c/src/zmalloc.c#L290)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

unsigned long
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 297 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlxqALR8krtcNHTJi_x:-Mly2GUWC7qdZqOQCMqI:b-896fix) ([raw file](https://github.com/memkeydb/memkeydb/blob/4dce305544a1270938db682fe072e27cc0308c1c/src/zmalloc.c#L297)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

MEMKIND_DAX_KMEM_NODES
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 309 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/154#-Mlxv3i_7xSIAQn3QP9T:-Mly2H8b6Rkb7e0869jA:b-896fix) ([raw file](https://github.com/memkeydb/memkeydb/blob/4dce305544a1270938db682fe072e27cc0308c1c/src/zmalloc.c#L309)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Fix whitespaces.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac and @PatKamin)

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @maciekpac)

___
*[src/zmalloc.c, line 295 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-Mlyj75GA3RWpKRMIEby:-Mlyj75GA3RWpKRMIEbz:b1hldym) ([raw file](https://github.com/memkeydb/memkeydb/blob/1f0c74d2a3b5dfb88e63d00d826da859cb9151d8/src/zmalloc.c#L295)):*
> ```C
> static void zmalloc_pmem_oom_handler(size_t size) {
>     unsigned long mask = 0;
>     memkind_dax_kmem_all_get_mbind_nodemask(NULL, &mask, 256);
> ```

Check return code.

**Review by maciekpac — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka)

___
*[-- commits, line 6 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-Mlyohxg7eD6TKTBy9eI):*
> ```
> Redis
> ```
MemKeyDB/MemTierDB
___
*[src/zmalloc.c, line 291 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlypeVx4rstuJ1TSb_9:-MlypeVx4rstuJ1TSb_A:b-udt72z) ([raw file](https://github.com/memkeydb/memkeydb/blob/63958acb72c7c4f93315563ab9a794830e8ddd6a/src/zmalloc.c#L291)):*
> ```C
> static void *zmalloc_pmem(size_t size) {
>     void *ptr = ztrymalloc_usable_pmem(size, NULL);
>     if (!ptr) zmalloc_oom_handler(size);
> ```

zmalloc_oom_handler is a static function pointer:

static void (*zmalloc_oom_handler)(size_t) = zmalloc_default_oom;

maybe we should just change an argument to zmalloc_set_oom_handler in server.c: main, instead of modifying the function in 6 places? there is also our pmem handler could directly call the function set in the file mentioned above
___
*[src/zmalloc.c, line 305 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlypHHCBGT_MTwKZCsF:-MlypHHD1I7Dw_2jKsrY:b20spkn) ([raw file](https://github.com/memkeydb/memkeydb/blob/1f0c74d2a3b5dfb88e63d00d826da859cb9151d8/src/zmalloc.c#L305)):*
> ```C
>         fprintf(stderr,"!!! please contact your system administrator for proper KMEM_DAX setup.\n");
>         fflush(stderr);
>         exit(1);
> ```

Can it be considered "graceful shutdown"?

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: all files reviewed, 4 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[-- commits, line 6 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-Mlyohxg7eD6TKTBy9eI):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

> ```
> Redis
> ```
MemKeyDB/MemTierDB
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 291 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlypeVx4rstuJ1TSb_9:-MlzFDsA0IRFsdbLCPVm:b-pxcziq) ([raw file](https://github.com/memkeydb/memkeydb/blob/63958acb72c7c4f93315563ab9a794830e8ddd6a/src/zmalloc.c#L291)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

zmalloc_oom_handler is a static function pointer:

static void (*zmalloc_oom_handler)(size_t) = zmalloc_default_oom;

maybe we should just change an argument to zmalloc_set_oom_handler in server.c: main, instead of modifying the function in 6 places? there is also our pmem handler could directly call the function set in the file mentioned above
</blockquote></details>

then you have to add additional parameter "is called from PMEM"?
___
*[src/zmalloc.c, line 295 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-Mlyj75GA3RWpKRMIEby:-MlzF7M62AtmIkzHhsYV:b-896fix) ([raw file](https://github.com/memkeydb/memkeydb/blob/1f0c74d2a3b5dfb88e63d00d826da859cb9151d8/src/zmalloc.c#L295)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Check return code.
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 305 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlypHHCBGT_MTwKZCsF:-MlzF87Y51OGLradNIbn:bup6o9s) ([raw file](https://github.com/memkeydb/memkeydb/blob/1f0c74d2a3b5dfb88e63d00d826da859cb9151d8/src/zmalloc.c#L305)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Can it be considered "graceful shutdown"?
</blockquote></details>

what do you propose?

**Review by maciekpac — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[src/zmalloc.c, line 291 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlypeVx4rstuJ1TSb_9:-MlziPpHDPd-AFY2xH6I:b-ea4964) ([raw file](https://github.com/memkeydb/memkeydb/blob/63958acb72c7c4f93315563ab9a794830e8ddd6a/src/zmalloc.c#L291)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

then you have to add additional parameter "is called from PMEM"?
</blockquote></details>

Good point!

We could also always display the message, but it's up to you to choose and, right now, I think that your original solution is better than my suggestion.
___
*[src/zmalloc.c, line 305 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlypHHCBGT_MTwKZCsF:-MlzgzyG4FdMGRMPzUxE:b-76zs2f) ([raw file](https://github.com/memkeydb/memkeydb/blob/1f0c74d2a3b5dfb88e63d00d826da859cb9151d8/src/zmalloc.c#L305)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

what do you propose? 
</blockquote></details>

serverPanic used by the default OOM handler is probably a much better idea; instead of just exiting, it does some other stuff that seems to be important" it unregisters signal handlers, prepares bug report, unlinks some files (server.pidfile), assures that we exit with correct signal and handle generation of coredump accordingly to config.

Functions to check:

src/debug.c: _serverPanic and bugReportEnd

Please note that we should probably use the macro "serverPanic", without the leading underscore.

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[-- commits, line 6 at r6](https://reviewable.io/reviews/memkeydb/memkeydb/154#-Mm1g4W9DJo7-fHueZDc):*
> ```
> and proces is closed
> ```
and the process

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: all files reviewed, 4 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[-- commits, line 6 at r6](https://reviewable.io/reviews/memkeydb/memkeydb/154#-Mm1g4W9DJo7-fHueZDc):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

> ```
> and proces is closed
> ```
and the process
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 291 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlypeVx4rstuJ1TSb_9:-Mm3MvncCtZx97edcOHx:b-896fix) ([raw file](https://github.com/memkeydb/memkeydb/blob/63958acb72c7c4f93315563ab9a794830e8ddd6a/src/zmalloc.c#L291)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Good point!

We could also always display the message, but it's up to you to choose and, right now, I think that your original solution is better than my suggestion.
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 305 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlypHHCBGT_MTwKZCsF:-Mm3MrsV9dX1j3eWyo8W:b-896fix) ([raw file](https://github.com/memkeydb/memkeydb/blob/1f0c74d2a3b5dfb88e63d00d826da859cb9151d8/src/zmalloc.c#L305)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

serverPanic used by the default OOM handler is probably a much better idea; instead of just exiting, it does some other stuff that seems to be important" it unregisters signal handlers, prepares bug report, unlinks some files (server.pidfile), assures that we exit with correct signal and handle generation of coredump accordingly to config.

Functions to check:

src/debug.c: _serverPanic and bugReportEnd

Please note that we should probably use the macro "serverPanic", without the leading underscore.
</blockquote></details>

Done.

**Review by PatKamin — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac)

**Review by maciekpac — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/zmalloc.c, line 305 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlypHHCBGT_MTwKZCsF:-MmMtDZg8Ub6PXJt_GYY:bgji7bs) ([raw file](https://github.com/memkeydb/memkeydb/blob/1f0c74d2a3b5dfb88e63d00d826da859cb9151d8/src/zmalloc.c#L305)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I can only see that "exit" was removed, no serverPanic was added - am I missing something?

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[src/zmalloc.c, line 305 at r4](https://reviewable.io/reviews/memkeydb/memkeydb/154#-MlypHHCBGT_MTwKZCsF:-MmMuIce2prKyOJx-_qP:b4lp5py) ([raw file](https://github.com/memkeydb/memkeydb/blob/1f0c74d2a3b5dfb88e63d00d826da859cb9151d8/src/zmalloc.c#L305)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I can only see that "exit" was removed, no serverPanic was added - am I missing something?
</blockquote></details>

zmalloc_oom_handler call everything needed in this situation.
Note that this function allocates some memory (which is weird because it is for OOM case :) ) so I had to disable allocating from PMEM first.

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
