### PR TITLE
Sync MemKeyDB with Redis 6.0.9.

### PR DESCRIPTION
**Pull request by jschmieg**
This change is [Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/57)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
Please close #54 and update the #55

> Reviewed 153 of 154 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/57#-:-MKsqaV70tjKtRmlHRlB:b-hp5dr7)* status: all files reviewed, 1 unresolved discussion (waiting on @jschmieg)

___
*[BUGS, line 1 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/57#-MKskXSo0pThagIu4QA5:-MKskXSo0pThagIu4QA6:b2lu356) ([raw file](https://github.com/memkeydb/memkeydb/blob/ebcb46d6bcf20ca68485a0763f7423a9b6dd7a1c/BUGS#L1)):*
> ```
> https://github.com/redis/redis/issues
> ```
Not exactly related to this port, but maybe "memkeydb" would be a good place to place it here instead of "redis" - could be done via separate commit also - up to you.

**Review by jschmieg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/57)* status: 153 of 154 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[BUGS, line 1 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/57#-MKskXSo0pThagIu4QA5:-MKt0pO0EZGTzkUdTcDm:b-896fix) ([raw file](https://github.com/memkeydb/memkeydb/blob/ebcb46d6bcf20ca68485a0763f7423a9b6dd7a1c/BUGS#L1)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> https://github.com/redis/redis/issues
> ```
Not exactly related to this port, but maybe "memkeydb" would be a good place to place it here instead of "redis" - could be done via separate commit also - up to you.
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/57)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kasiawasiuta — APPROVED** [review]
> Reviewed 152 of 154 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/57)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
