### PR TITLE
Add a separate OOM handler for PMEM

### PR DESCRIPTION
**Pull request by bratpiorka**
- this handler first checks if there are any PMEM nodes in the system available for use by Memkind
  and if not - a descriptive error message is printed and allocator is switched to DRAM-only mode
- then the default OOM handler is called

---
This change is [Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/162)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
already reviewed in #154 

> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/162#-:-MmSCWLa7bQcmzwDbS_V:bmyn9zo)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @maciekpac and @PatKamin)

**Review by PatKamin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Review by maciekpac — APPROVED** [review]

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/162)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[-- commits, line 9 at r2](https://reviewable.io/reviews/memkeydb/memkeydb/162#-MmqIeyp3kxyyZ5k4lV0):*
I couldn't reproduce this compilation failure. Is this change needed? What are the warnings/errors that it fixes?

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/162)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[-- commits, line 9 at r2](https://reviewable.io/reviews/memkeydb/memkeydb/162#-MmqIeyp3kxyyZ5k4lV0):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I couldn't reproduce this compilation failure. Is this change needed? What are the warnings/errors that it fixes?
</blockquote></details>

/usr/bin/ld: pmem.o:/home/rrudnick/memKeyDB/src/sds.h:37: multiple definition of `SDS_NOINIT'; quicklist.o:/home/rrudnick/memKeyDB/src/sds.h:37: first defined here

notice that SDS_NOINIT is defined both in sds.h AND sds.c

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
