### PR TITLE
Update README with link to blog

### PR DESCRIPTION
**Pull request by jschmieg**
This change is [Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/53)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/53)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @guoanwu, @jschmieg, @kasiawasiuta, @michalbiesek, and @PatKamin)

___
*[README.md, line 10 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/53#-MKEtAYy4WcmWe79fJFT:-MKEtAYy4WcmWe79fJFU:b-jw1o9t) ([raw file](https://github.com/memkeydb/memkeydb/blob/1c643328827b8119cf7181c44a8c9d39b46d6da5/README.md#L10)):*
> ```
> entry:
> ```
[entry](https://pmem.io/2020/09/25/memkeydb.html).

Similar scheme as above with redis.io

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/53)* status: all files reviewed, 2 unresolved discussions (waiting on @guoanwu, @jschmieg, @kasiawasiuta, and @michalbiesek)

___
*[README.md, line 10 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/53#-MKEtAYy4WcmWe79fJFT:-MKEuO_817R1s49vhe6I:bf18tdr) ([raw file](https://github.com/memkeydb/memkeydb/blob/1c643328827b8119cf7181c44a8c9d39b46d6da5/README.md#L10)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> entry:
> ```
[entry](https://pmem.io/2020/09/25/memkeydb.html).

Similar scheme as above with redis.io
</blockquote></details>

Even better: [blog entry](https://pmem.io/2020/09/25/memkeydb.html)
___
*[README.md, line 10 at r2](https://reviewable.io/reviews/memkeydb/memkeydb/53#-MKEuhSiE33LwMGBpiZJ:-MKEuhSiE33LwMGBpiZK:bb3ivq8) ([raw file](https://github.com/memkeydb/memkeydb/blob/3a9f856c4e358886e6d5f847ea85592dd49a18d8/README.md#L10)):*
> ```Markdown
> The data stored on the medium is volatile and the persistency is preserved with RDB/AOF mechanism.
> 
> For details please read this blog [entry](https://pmem.io/2020/09/25/memkeydb.html).
> ```

nit: Could be even better: [blog entry](https://pmem.io/2020/09/25/memkeydb.html)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/53#-:-MKF-xZR1bmsSbbC43Lm:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @guoanwu, @jschmieg, @kasiawasiuta, @michalbiesek, and @PatKamin)

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/53)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @guoanwu, @jschmieg, @kasiawasiuta, and @PatKamin)

**Review by kasiawasiuta — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/53)* status: all files reviewed, 1 unresolved discussion (waiting on @guoanwu and @jschmieg)

**Pull request merged**
